---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskr
    app.kubernetes.io/component: flaskr
    app.kubernetes.io/instance: flaskr
  name: flaskr
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: flaskr
  strategy: {}
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        deployment: flaskr
    spec:
      containers:
      - image: flaskr:latest
        name: flaskr
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskr
    app.kubernetes.io/component: flaskr
    app.kubernetes.io/instance: flaskr
  name: flaskr
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: flaskr
